### ISSUE TITLE
css颜色属性：currentColor

### ISSUE THREAD

**Issue by xklsky** [xklsky/xklsky.github.io#1]
currentColor是一个属性值，代表当前元素的color属性的值。

```css
.box {
  color: red;
  border: 1px solid currentColor;
  box-shadow: 0 0 2px 2px currentColor;
}
```
上面代码，border和box-shadow的颜色都与color保持一致。这种写法的好处是，如果要修改color，只要修改一处就可以了，不用修改三个地方。

currentColor的另一个用处，是让衍生类都继承基类的颜色。

```css
.box {
    color: red;
}
.box .child-1 {
    background: currentColor;
}
.box .child-2 {
    color: currentColor;
    border 1px solid currentColor;
}
```
伪元素也可以使用currentColor。

```css
.box {
    color: red;
}
.box:before {
    color: currentColor;
    border: 1px solid currentColor;
}
```
